export enum DocumentType {
  LOGO = 'logo',
  CERTIFICATE = 'certificate',
  CONSTANCY = 'constancy',
  TAX_RECEIPT = 'tax_receipt',
  INVOICE = 'invoice',
  CONTRACT = 'contract',
  IDENTIFICATION = 'identification',
  PROOF_ADDRESS = 'proof_address',
  LOGO_DARK = 'logo_dark',
  LOGO_LIGHT = 'logo_light',
  FAVICON = 'favicon',
  ICON = 'icon',
  BANNER = 'banner',
  IMAGE = 'image',
  PDF = 'pdf',
  OTHER = 'other',
}
